#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
==============================================================
PROJECT:
Explainable Machine Learning Model for Distillery Effluent
Treatment and Management

MODULE:
07_Model_Explainability.py

DESCRIPTION
--------------------------------------------------------------
This module explains the predictions generated by the trained
machine learning models.

Explainability techniques implemented include:

1. Built-in Feature Importance
2. Permutation Feature Importance
3. SHAP (SHapley Additive exPlanations)
4. LIME (Local Interpretable Model-Agnostic Explanations)
5. Partial Dependence Plots (PDP)
6. Individual Conditional Expectation (ICE)

Outputs are automatically saved under:

Results/
    Explainability/
        FeatureImportance/
        Permutation/
        SHAP/
        LIME/
        PDP/
        ICE/

Author:
Clifford Otieno Obiewa
MSc Information Technology
Kabarak University
==============================================================
"""

###############################################################
# IMPORT LIBRARIES
###############################################################

import warnings
from pathlib import Path

import joblib
import lime
import lime.lime_tabular
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap

from sklearn.inspection import (
    PartialDependenceDisplay,
    permutation_importance,
)

warnings.filterwarnings("ignore")

plt.style.use("ggplot")

###############################################################
# PROJECT DIRECTORIES
###############################################################

BASE_DIR = Path.cwd()

DATA_DIR = BASE_DIR / "Dataset"
MODEL_DIR = BASE_DIR / "Models"
RESULTS_DIR = BASE_DIR / "Results"

EXPLAIN_DIR = RESULTS_DIR / "Explainability"

FEATURE_DIR = EXPLAIN_DIR / "FeatureImportance"
PERM_DIR = EXPLAIN_DIR / "Permutation"
SHAP_DIR = EXPLAIN_DIR / "SHAP"
LIME_DIR = EXPLAIN_DIR / "LIME"
PDP_DIR = EXPLAIN_DIR / "PDP"
ICE_DIR = EXPLAIN_DIR / "ICE"

###############################################################
# CREATE OUTPUT DIRECTORIES
###############################################################

directories = [
    RESULTS_DIR,
    EXPLAIN_DIR,
    FEATURE_DIR,
    PERM_DIR,
    SHAP_DIR,
    LIME_DIR,
    PDP_DIR,
    ICE_DIR,
]

for folder in directories:
    folder.mkdir(parents=True, exist_ok=True)

print("=" * 65)
print("MODEL EXPLAINABILITY")
print("=" * 65)

###############################################################
# LOAD DATASET
###############################################################

print("\nLoading cleaned dataset...")

DATA_FILE = DATA_DIR / "distillery_clean.csv"

if not DATA_FILE.exists():
    raise FileNotFoundError(
        f"\nDataset not found:\n{DATA_FILE}"
    )

df = pd.read_csv(DATA_FILE)

print(f"Dataset loaded successfully.")
print(f"Dataset Shape : {df.shape}")

###############################################################
# LOAD TRAINING DATA
###############################################################

print("\nLoading training datasets...")

required_files = {
    "X_train": DATA_DIR / "X_train.pkl",
    "X_test": DATA_DIR / "X_test.pkl",
    "Y_train": DATA_DIR / "Y_train.pkl",
    "Y_test": DATA_DIR / "Y_test.pkl",
}

for name, path in required_files.items():
    if not path.exists():
        raise FileNotFoundError(f"Missing file:\n{path}")

X_train = joblib.load(required_files["X_train"])
X_test = joblib.load(required_files["X_test"])
Y_train = joblib.load(required_files["Y_train"])
Y_test = joblib.load(required_files["Y_test"])

print("Training datasets loaded.")

###############################################################
# LOAD SCALER
###############################################################

print("\nLoading scaler...")

SCALER_FILE = MODEL_DIR / "Scaler.pkl"

if not SCALER_FILE.exists():
    raise FileNotFoundError(
        f"Scaler not found:\n{SCALER_FILE}"
    )

scaler = joblib.load(SCALER_FILE)

print("Scaler loaded.")

###############################################################
# LOAD BEST MODEL
###############################################################

print("\nLoading trained model...")

MODEL_FILE = MODEL_DIR / "Best_Model.pkl"

if not MODEL_FILE.exists():
    raise FileNotFoundError(
        f"Model not found:\n{MODEL_FILE}"
    )

model = joblib.load(MODEL_FILE)

print("Best model loaded successfully.")

###############################################################
# SCALE TEST DATA
###############################################################

print("\nScaling datasets...")

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

###############################################################
# FEATURE NAMES
###############################################################

if isinstance(X_train, pd.DataFrame):
    feature_names = X_train.columns.tolist()
else:
    feature_names = [f"Feature_{i+1}" for i in range(X_train.shape[1])]

print(f"\nNumber of Features : {len(feature_names)}")

###############################################################
# UTILITY FUNCTIONS
###############################################################

def save_plot(filepath):
    """
    Save matplotlib figure.
    """
    plt.tight_layout()
    plt.savefig(filepath, dpi=300, bbox_inches="tight")
    plt.close()


def print_section(title):
    """
    Print formatted section heading.
    """
    print("\n" + "=" * 65)
    print(title)
    print("=" * 65)


###############################################################
# INITIALIZATION SUMMARY
###############################################################

print_section("INITIALIZATION SUMMARY")

print(f"Dataset Records      : {len(df):,}")
print(f"Training Samples     : {len(X_train):,}")
print(f"Testing Samples      : {len(X_test):,}")
print(f"Number of Features   : {len(feature_names)}")

print("\nInitialization completed successfully.")
print("Ready for explainability analysis.")
print("\nModel Type:")
print(type(model))

print("\nModel Class:")
print(model.__class__.__name__)
###############################################################
# PART 2
# GLOBAL FEATURE IMPORTANCE
###############################################################

print_section("GLOBAL FEATURE IMPORTANCE")

# Get individual models
estimators = model.estimators_

print(f"Number of target models: {len(estimators)}")

target_names = list(Y_train.columns)

###############################################################
# FEATURE IMPORTANCE FOR EACH TARGET
###############################################################

for target_name, estimator in zip(target_names, estimators):

    print(f"\nProcessing: {target_name}")

    ###########################################################
    # CHECK MODEL SUPPORT
    ###########################################################

    if hasattr(estimator, "feature_importances_"):

        importance = estimator.feature_importances_

    elif hasattr(estimator, "coef_"):

        importance = np.abs(estimator.coef_)

    else:

        print(f"Skipping {target_name} (no feature importance available)")
        continue

    ###########################################################
    # CREATE DATAFRAME
    ###########################################################

    importance_df = pd.DataFrame({
        "Feature": feature_names,
        "Importance": importance
    })

    importance_df = importance_df.sort_values(
        "Importance",
        ascending=False
    )

    ###########################################################
    # DISPLAY TOP FEATURES
    ###########################################################

    print(importance_df.head(10))

    ###########################################################
    # SAVE CSV
    ###########################################################

    csv_name = FEATURE_DIR / f"{target_name}_FeatureImportance.csv"

    importance_df.to_csv(
        csv_name,
        index=False
    )

    ###########################################################
    # PLOT
    ###########################################################

    plt.figure(figsize=(10,7))

    top20 = importance_df.head(20)

    plt.barh(
        top20["Feature"],
        top20["Importance"]
    )

    plt.gca().invert_yaxis()

    plt.title(f"{target_name} Feature Importance")

    plt.xlabel("Importance")

    save_plot(
        FEATURE_DIR / f"{target_name}_FeatureImportance.png"
    )

    print(f"{target_name} completed.")

print("\nGlobal Feature Importance completed successfully.")


###############################################################
# PART 3
# PERMUTATION FEATURE IMPORTANCE
###############################################################

print_section("PERMUTATION FEATURE IMPORTANCE")

###############################################################
# PERMUTATION IMPORTANCE FOR EACH TARGET
###############################################################

for i, (target_name, estimator) in enumerate(zip(target_names, estimators)):

    print(f"\nProcessing: {target_name}")

    ###########################################################
    # SELECT TARGET
    ###########################################################

    y_test_target = Y_test.iloc[:, i]

    ###########################################################
    # COMPUTE PERMUTATION IMPORTANCE
    ###########################################################

    perm = permutation_importance(
        estimator,
        X_test_scaled,
        y_test_target,
        scoring="r2",
        n_repeats=10,
        random_state=42,
        n_jobs=-1
    )

    ###########################################################
    # CREATE DATAFRAME
    ###########################################################

    perm_df = pd.DataFrame({
        "Feature": feature_names,
        "Importance": perm.importances_mean,
        "Std": perm.importances_std
    })

    perm_df = perm_df.sort_values(
        by="Importance",
        ascending=False
    ).reset_index(drop=True)

    ###########################################################
    # DISPLAY RESULTS
    ###########################################################

    print("\nTop 10 Features")

    print(perm_df.head(10))

    ###########################################################
    # SAVE CSV
    ###########################################################

    csv_file = PERM_DIR / f"{target_name}_PermutationImportance.csv"

    perm_df.to_csv(
        csv_file,
        index=False
    )

    ###########################################################
    # PLOT
    ###########################################################

    plt.figure(figsize=(10,7))

    top20 = perm_df.head(20)

    plt.barh(
        top20["Feature"],
        top20["Importance"],
        xerr=top20["Std"]
    )

    plt.gca().invert_yaxis()

    plt.xlabel("Permutation Importance")

    plt.ylabel("Feature")

    plt.title(
        f"Permutation Feature Importance\n{target_name}"
    )

    save_plot(
        PERM_DIR / f"{target_name}_PermutationImportance.png"
    )

    ###########################################################
    # SAVE TOP 10
    ###########################################################

    top20.to_csv(
        PERM_DIR / f"{target_name}_Top20Permutation.csv",
        index=False
    )

    print(f"{target_name} completed.")

###############################################################
# SUMMARY
###############################################################

print("\nPermutation Feature Importance Completed Successfully.")


###############################################################
# PART 4
# SHAP EXPLAINABILITY
###############################################################

print_section("SHAP EXPLAINABILITY")

###############################################################
# USE A SAMPLE FOR FASTER COMPUTATION
###############################################################

sample_size = min(200, len(X_test_scaled))

X_sample = X_test_scaled[:sample_size]

###############################################################
# SHAP FOR EACH TARGET
###############################################################

for i, (target_name, estimator) in enumerate(zip(target_names, estimators)):

    print(f"\nGenerating SHAP explanations for {target_name}")

    ###########################################################
    # CREATE SHAP EXPLAINER
    ###########################################################

    explainer = shap.TreeExplainer(estimator)

    ###########################################################
    # COMPUTE SHAP VALUES
    ###########################################################

    shap_values = explainer.shap_values(X_sample)

    ###########################################################
    # SAVE SHAP VALUES
    ###########################################################

    shap_df = pd.DataFrame(
        shap_values,
        columns=feature_names
    )

    shap_df.to_csv(
        SHAP_DIR / f"{target_name}_SHAP_Values.csv",
        index=False
    )

    ###########################################################
    # SHAP SUMMARY BAR
    ###########################################################

    plt.figure(figsize=(10, 7))

    shap.summary_plot(
        shap_values,
        X_sample,
        feature_names=feature_names,
        plot_type="bar",
        show=False
    )

    save_plot(
        SHAP_DIR / f"{target_name}_SHAP_Bar.png"
    )

    ###########################################################
    # SHAP SUMMARY DOT
    ###########################################################

    plt.figure(figsize=(10, 7))

    shap.summary_plot(
        shap_values,
        X_sample,
        feature_names=feature_names,
        show=False
    )

    save_plot(
        SHAP_DIR / f"{target_name}_SHAP_Summary.png"
    )

    ###########################################################
    # SHAP WATERFALL
    ###########################################################

    explanation = shap.Explanation(
        values=shap_values[0],
        base_values=explainer.expected_value,
        data=X_sample[0],
        feature_names=feature_names
    )

    plt.figure(figsize=(9, 6))

    shap.plots.waterfall(
        explanation,
        show=False
    )

    save_plot(
        SHAP_DIR / f"{target_name}_SHAP_Waterfall.png"
    )

    ###########################################################
    # SHAP DECISION PLOT
    ###########################################################

    plt.figure(figsize=(10, 6))

    shap.decision_plot(
        explainer.expected_value,
        shap_values[0],
        X_sample[0],
        feature_names=feature_names,
        show=False
    )

    save_plot(
        SHAP_DIR / f"{target_name}_SHAP_Decision.png"
    )

    print(f"{target_name} completed.")

###############################################################
# COMPLETION
###############################################################

print("\nSHAP analysis completed successfully.")


###############################################################
# PART 5
# LIME EXPLAINABILITY
###############################################################

print_section("LIME EXPLAINABILITY")

###############################################################
# CREATE LIME EXPLAINER
###############################################################

lime_explainer = lime.lime_tabular.LimeTabularExplainer(

    training_data=np.array(X_train_scaled),

    feature_names=feature_names,

    mode="regression",

    discretize_continuous=True,

    random_state=42

)

###############################################################
# LIME FOR EACH TARGET
###############################################################

for i, (target_name, estimator) in enumerate(zip(target_names, estimators)):

    print(f"\nGenerating LIME explanation for {target_name}")

    ###########################################################
    # EXPLAIN FIRST TEST INSTANCE
    ###########################################################

    explanation = lime_explainer.explain_instance(

        data_row=X_test_scaled[0],

        predict_fn=estimator.predict,

        num_features=min(10, len(feature_names))

    )

    ###########################################################
    # SAVE HTML REPORT
    ###########################################################

    html_file = LIME_DIR / f"{target_name}_LIME.html"

    explanation.save_to_file(str(html_file))

    ###########################################################
    # SAVE FEATURE WEIGHTS
    ###########################################################

    lime_df = pd.DataFrame(

        explanation.as_list(),

        columns=["Feature", "Weight"]

    )

    csv_file = LIME_DIR / f"{target_name}_LIME.csv"

    lime_df.to_csv(

        csv_file,

        index=False

    )

    ###########################################################
    # PLOT FEATURE CONTRIBUTIONS
    ###########################################################

    plt.figure(figsize=(9,6))

    plt.barh(

        lime_df["Feature"],

        lime_df["Weight"]

    )

    plt.gca().invert_yaxis()

    plt.xlabel("Contribution")

    plt.ylabel("Feature")

    plt.title(f"LIME Explanation\n{target_name}")

    save_plot(

        LIME_DIR / f"{target_name}_LIME.png"

    )

    print(f"{target_name} completed.")

###############################################################
# SUMMARY
###############################################################

print("\nLIME explainability completed successfully.")


###############################################################
# PART 6
# PARTIAL DEPENDENCE PLOTS (PDP)
###############################################################

print_section("PARTIAL DEPENDENCE PLOTS (PDP)")

###############################################################
# GENERATE PDP FOR EACH TARGET
###############################################################

for target_name, estimator in zip(target_names, estimators):

    print(f"\nGenerating PDPs for {target_name}")

    ###########################################################
    # LOAD FEATURE IMPORTANCE RANKING
    ###########################################################

    importance_file = FEATURE_DIR / f"{target_name}_FeatureImportance.csv"

    if not importance_file.exists():

        print(f"Feature importance file missing for {target_name}")

        continue

    importance_df = pd.read_csv(importance_file)

    ###########################################################
    # SELECT TOP 5 FEATURES
    ###########################################################

    top_features = importance_df.head(5)["Feature"].tolist()

    ###########################################################
    # CREATE PDP FOR EACH FEATURE
    ###########################################################

    for feature in top_features:

        print(f"   Processing {feature}")

        try:

            fig, ax = plt.subplots(figsize=(8,6))

            PartialDependenceDisplay.from_estimator(

                estimator,

                X_test_scaled,

                features=[feature_names.index(feature)],

                feature_names=feature_names,

                ax=ax

            )

            plt.title(f"{target_name}\nPartial Dependence: {feature}")

            save_plot(

                PDP_DIR / f"{target_name}_{feature}_PDP.png"

            )

        except Exception as e:

            print(f"   Skipped {feature}: {e}")

    print(f"{target_name} completed.")

###############################################################
# SUMMARY
###############################################################

print("\nPartial Dependence Plot generation completed successfully.")


###############################################################
# PART 7
# INDIVIDUAL CONDITIONAL EXPECTATION (ICE) PLOTS
###############################################################

print_section("INDIVIDUAL CONDITIONAL EXPECTATION (ICE)")

###############################################################
# GENERATE ICE PLOTS
###############################################################

for target_name, estimator in zip(target_names, estimators):

    print(f"\nGenerating ICE plots for {target_name}")

    ###########################################################
    # LOAD FEATURE IMPORTANCE
    ###########################################################

    importance_file = FEATURE_DIR / f"{target_name}_FeatureImportance.csv"

    if not importance_file.exists():

        print(f"Feature importance file not found for {target_name}")

        continue

    importance_df = pd.read_csv(importance_file)

    ###########################################################
    # TOP THREE FEATURES
    ###########################################################

    top_features = importance_df.head(3)["Feature"].tolist()

    ###########################################################
    # CREATE ICE FOR EACH FEATURE
    ###########################################################

    for feature in top_features:

        print(f"   Processing {feature}")

        try:

            fig, ax = plt.subplots(figsize=(8,6))

            PartialDependenceDisplay.from_estimator(

                estimator,

                X_test_scaled,

                features=[feature_names.index(feature)],

                feature_names=feature_names,

                kind="individual",

                subsample=50,

                random_state=42,

                ax=ax

            )

            plt.title(f"{target_name}\nICE Plot: {feature}")

            save_plot(

                ICE_DIR / f"{target_name}_{feature}_ICE.png"

            )

        except Exception as e:

            print(f"   Skipped {feature}: {e}")

    print(f"{target_name} completed.")

###############################################################
# SUMMARY
###############################################################

print("\nICE plot generation completed successfully.")


###############################################################
# PART 8
# EXPLAINABILITY SUMMARY REPORT
###############################################################

print_section("EXPLAINABILITY SUMMARY REPORT")

###############################################################
# COMBINE FEATURE IMPORTANCE TABLES
###############################################################

summary_tables = []

for target_name in target_names:

    file_path = FEATURE_DIR / f"{target_name}_FeatureImportance.csv"

    if not file_path.exists():
        continue

    df_feature = pd.read_csv(file_path)

    df_feature = df_feature.head(10)

    df_feature.insert(0, "Target", target_name)

    summary_tables.append(df_feature)

###############################################################
# CREATE MASTER TABLE
###############################################################

if len(summary_tables) > 0:

    summary_df = pd.concat(
        summary_tables,
        ignore_index=True
    )

    summary_csv = EXPLAIN_DIR / "Explainability_Summary.csv"

    summary_df.to_csv(
        summary_csv,
        index=False
    )

    print(f"Summary CSV saved:\n{summary_csv}")

###############################################################
# EXPORT TO EXCEL
###############################################################

excel_file = EXPLAIN_DIR / "Explainability_Report.xlsx"

with pd.ExcelWriter(excel_file) as writer:

    for target_name in target_names:

        file_path = FEATURE_DIR / f"{target_name}_FeatureImportance.csv"

        if file_path.exists():

            pd.read_csv(file_path).to_excel(
                writer,
                sheet_name=target_name[:31],
                index=False
            )

    if len(summary_tables) > 0:

        summary_df.to_excel(
            writer,
            sheet_name="Summary",
            index=False
        )

print(f"Excel report saved:\n{excel_file}")

###############################################################
# CREATE TEXT REPORT
###############################################################

report_file = EXPLAIN_DIR / "Explainability_Report.txt"

with open(report_file, "w") as report:

    report.write("=" * 70 + "\n")
    report.write("EXPLAINABLE MACHINE LEARNING REPORT\n")
    report.write("=" * 70 + "\n\n")

    report.write("PROJECT\n")
    report.write(
        "Explainable Machine Learning Model for Distillery "
        "Effluent Treatment and Management\n\n"
    )

    report.write("DATASET SUMMARY\n")
    report.write(f"Records : {len(df)}\n")
    report.write(f"Features : {len(feature_names)}\n")
    report.write(f"Targets : {len(target_names)}\n\n")

    report.write("TARGET VARIABLES\n")

    for target in target_names:
        report.write(f" - {target}\n")

    report.write("\n")

    report.write("EXPLAINABILITY METHODS IMPLEMENTED\n")
    report.write("1. Built-in Feature Importance\n")
    report.write("2. Permutation Feature Importance\n")
    report.write("3. SHAP\n")
    report.write("4. LIME\n")
    report.write("5. Partial Dependence Plots\n")
    report.write("6. Individual Conditional Expectation Plots\n\n")

    report.write("OUTPUT DIRECTORIES\n")
    report.write(f"Feature Importance : {FEATURE_DIR}\n")
    report.write(f"Permutation        : {PERM_DIR}\n")
    report.write(f"SHAP               : {SHAP_DIR}\n")
    report.write(f"LIME               : {LIME_DIR}\n")
    report.write(f"PDP                : {PDP_DIR}\n")
    report.write(f"ICE                : {ICE_DIR}\n")

print(f"Text report saved:\n{report_file}")

###############################################################
# FINAL CONSOLE SUMMARY
###############################################################

print("\n" + "=" * 70)
print("MODEL EXPLAINABILITY COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nGenerated Outputs")

print("✓ Feature Importance")
print("✓ Permutation Importance")
print("✓ SHAP")
print("✓ LIME")
print("✓ Partial Dependence Plots")
print("✓ Individual Conditional Expectation Plots")
print("✓ CSV Reports")
print("✓ Excel Report")
print("✓ Text Report")

print("\nResults saved under:")
print(EXPLAIN_DIR)

print("\nEnd of 07_Model_Explainability.py")